name: Build and Deploy job
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Test code
        run: make test
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: 386
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build standard binaries
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildArtifact_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./bin/website-cookie-analyzer*
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Download Build artifacts
        uses: actions/download-artifact@v5
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
