name: Build and Deploy job
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.20.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test code
        run: make test
  build:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
        goos:
          - linux
          - amd64
          - 386
          - arm64
          - arm
        goarch:
          - linux
          - windows
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: 386
    runs-on: ${{ matrix.os }}
    needs: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build standard binaries
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildArtifact_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./bin/website-cookie-analyzer*
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Build artifacts
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
